---
title: "A tutorial on Lipid Structure Enrichment Analysis (LSEA)"
output: rmarkdown::github_document
vignette: >
  %\VignetteIndexEntry{demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
### load package and example data
```{r, warning = FALSE}
library(lsea)
# load example lipidomic composition data generated by adding random noise to real data
data(comp_data)
# load group labels (A or B) for differential testing and enrichment analysis
data(labels)
```
## CLR transformation
```{r}
#transform composition data (features x samples) using centered log-ratio transformation
# note: this is not for normalized abundance data!!
clr_data <- lsea::clr.transform(comp_data)
```
## Differential composition testing
```{r, warning = FALSE, message = FALSE}
# to perform a paired t-test (samples must be ordered by pair)
t_df <- lsea::two.group.row.test(clr_data, labels, test = "t", paired = TRUE)
# to perform unpaired wilcox test
# note: wilcox test will throw warnings for every row with ties, so suppress those warnings
w_df <- suppressWarnings(lsea::two.group.row.test(clr_data, labels, test = "w", paired = FALSE))
```
##### t-test results ordered by p-value
```{r, echo = FALSE}
knitr::kable(head(t_df[order(t_df$pvalue),]))
```
##### Wilcoxon test results ordered by p-value
```{r, echo = FALSE}
knitr::kable(head(w_df[order(w_df$pvalue),]))
```
## LSEA
```{r, warning = FALSE, message = FALSE}
# we can use the t-statistic to rank lipid species and perform enrichment analysis using the GSEA algorithm
# note: the returned Wilcoxon statistic is not directional
res <- lsea::lsea(t_df, rnk_name = "stat")
```
##### Top 5 positive results
```{r, echo = FALSE}
knitr::kable(res[1:5,1:5])
```
##### Top 5 negative results
```{r, echo = FALSE}
knitr::kable(res[279:284,1:5])
```
### lipid species structure annotation
```{r}
# LSEA works by annotating the provided lipid species based on their LIPIDMAPS-style name
lipid_anno <- lsea::annotate.lipid.species(rownames(t_df[order(t_df$pvalue),]))
```

```{r, echo = FALSE}
knitr::kable(head(lipid_anno, 10))
```
### Visualizing differential lipid species enrichment
```{r}
# for the purposes of this example we will raise the adjusted p-value threshold
lsea::structure.enrichment.plot(
  de_tbl = t_df, anno_tbl = lipid_anno, group_names = c("A", "B"),
  p_thresh = 0.75, color_pal = c("dodgerblue", "firebrick")
)
```

